use_frameworks!

platform :ios, '8.0'

target 'RYGlobalUIUtilsDemo_Example' do
  pod 'RYGlobalUIUtilsDemo', :path => '../'

  target 'RYGlobalUIUtilsDemo_Tests' do
    inherit! :search_paths

    
  end
end
